### ISSUE TITLE
Missing stuff in the readme

### ISSUE THREAD

**Issue by andybak** [yourlabs/crudlfap#13]
class ServerUpdateView(ServerOwnerRequired, crudlfap.UpdateView):

Where does ServerOwnerRequired come from?

    ServerCreateView.factory(allow=authenticated),

What should ServerCreateView look like? Same for ServerUpdateView, ServerDeleteView

This might make sense if I went through the example app - but then you need to decide if the readme getting started stands on it's own - or whether you need to say "examine the example app before reading this".

I'll keep ploughing on. I'm sure it will start to make sense but I thought my initial feedback coming to it fresh would be valuable for you.

**Comment by jpic** [comment]
I recon this README references too much stuff which comes from my imagination.

I'm really sorry about the current state of documentation right now, but it's has to be improved because crudlfa+ is to be used in production in a governmental open source project (sgmap/mrs)

**Comment by jpic** [comment]
Hi  Andy !

I forgot to mention that rtfd built the docs : http://crudlfap.readthedocs.io/en/latest/

Hope this helps

**Comment by jpic** [comment]
This is all from a private project, and not up to date (will be deleted soon), documentation will improve over time, meanwhile, see crudlfap_auth app or examples in crudlfap_example
