### ISSUE TITLE
Permission integration

### ISSUE THREAD

**Issue by jpic** [yourlabs/crudlfap#20]
Currently, CRUDLFA+ has a very basic permission system. However, it doesn't use the django.contrib.auth permission system and that's a bit a shame.

CRUDLFA+ should be able to:

- add permission per view,
- use Django's permission check mechanism.

If it uses Django permission check mechanism, it won't matter if the project uses django-guardian (store ACL in DB) or django-rules (ACL in python).

**Comment by melvyn-sopacua** [comment]
Django permissions are class level, not object level last time I checked. So, patterns like "User can only modify articles it created herself" cannot be done. Need to check if this is still the case for 2.0.

**Comment by jpic** [comment]
Well it is possible in the admin: https://docs.djangoproject.com/en/2.0/topics/auth/default/#topic-authorization

And also django-rules: https://github.com/dfunckt/django-rules

So I was wondering about this yesterday, started converting the song app to django-rules, should we have a ModelAdminRouterAdapter that would reuse a ModelAdmin class ? That might help a lot of users migrating, but not my priority for tuesday, so I started converting the song app to django-rules in a branch.

```
diff --git a/src/crudlfap/settings.py b/src/crudlfap/settings.py
index 79ae327..34ef90c 100644
--- a/src/crudlfap/settings.py
+++ b/src/crudlfap/settings.py
@@ -44,6 +44,7 @@ INSTALLED_APPS = [
     'betterforms',
     'bootstrap3',
     'material',
+    'rules.apps.AutodiscoverRulesConfig',
 ]

 # CRUDLFA+ optional dependencies
@@ -185,6 +186,10 @@ AUTH_PASSWORD_VALIDATORS = [
     },
 ]

+AUTHENTICATION_BACKENDS = (
+    'rules.permissions.ObjectPermissionBackend',
+    'django.contrib.auth.backends.ModelBackend',
+)

diff --git a/src/crudlfap_example/song/rules.py b/src/crudlfap_example/song/rules.py
new file mode 100644
index 0000000..3ee176f
--- /dev/null
+++ b/src/crudlfap_example/song/rules.py
@@ -0,0 +1,13 @@
+import rules
+
+
+@rules.predictate
+def song_owner(user, song):
+    return song.owner == user
+
+
+rules.add_perm('song.add_song', is_authenticated)
+rules.add_perm('song.detail_song', is_staff | song_owner)
+rules.add_perm('song.change_song', is_staff | song_owner)
+rules.add_perm('song.delete_song', is_staff | song_owner)
+rules.add_perm('song', is_authenticated)
diff --git a/src/crudlfap_example/song/urls.py b/src/crudlfap_example/song/urls.py
index 7e5345d..105d107 100644
--- a/src/crudlfap_example/song/urls.py
+++ b/src/crudlfap_example/song/urls.py
@@ -3,17 +3,7 @@ from crudlfap import crudlfap
 from .models import Song


-def authenticated(view):
-    return True if view.request.user.is_authenticated else False
-
-
-def owner_or_staff(view):
-    return view.request.user.is_staff or view.object.owner == view.request.user
-
-
 class SongUpdateView(crudlfap.UpdateView):
-    allow = owner_or_staff
-
     def get_fields(self):
         if self.request.user.is_staff:
             return ['name', 'owner']
@@ -24,16 +14,19 @@ class SongUpdateView(crudlfap.UpdateView):
 class SongRouter(crudlfap.Router):
     fields = '__all__'
     icon = 'music'
-
     views = [
-        crudlfap.DeleteView.factory(allow=owner_or_staff),
+        crudlfap.DeleteView,
         crudlfap.UpdateView,
-        crudlfap.CreateView.factory(allow=authenticated),
-        crudlfap.DetailView.factory(allow=authenticated),
+        crudlfap.CreateView,
+        crudlfap.DetailView,
         crudlfap.FilterTables2ListView.factory(
             filter_fields=['artist'],
             search_fields=['artist__name', 'name'],
         ),
     ]

+    def get_queryset(self, user):
+        return Song.objects.filter(owner=user)
+
+
 urlpatterns = SongRouter(Song).urlpatterns()
```

But of course that's just the configuration, the router needs modification to use this.
```

**Comment by spapas** [comment]
Why not integrate a perm system similar to django-rules-light (https://github.com/yourlabs/django-rules-light)? I use it to almost all my projects that need perms of the form "object viewable by all but editable by owner and users belonging to the admin group" (actually most of the times there's also a status involved).

I've never really needed true object level (acl) permissions and I can't think of a use case unless you are creating an OS!

 The only disadvantage of django-rules-light is lack of integration of permissions with querying, however this is also a problem with object level perms and is easily fixed if you are careful of your queries.

**Comment by jpic** [comment]
Yes but django-rules is better at that than django-rules-light (and also we don't maintain it)

**Comment by melvyn-sopacua** [comment]
No, the documentation you linked actually proves my point. It is still class level based. You either have permission to delete / add / modify **all instances of a model** or you don't. There's no built-in way into Django that facilitates CRUD for **a specific model instance**.

**Comment by melvyn-sopacua** [comment]
> Why not integrate a perm system similar to django-rules-light?

Depends on the goal of the project and this should be made clear. Do we force a permission implementation on users or provide API handles with a default implementation? The upside for users would be that they do not have to migrate their existing permission implementation but simply route the calls.

**Comment by jpic** [comment]
Exactly, so the solutions would be:

- django-rules
- django-guardian
- ModelAdmin

Also, they should be able to configure everything in the Router without depending on any of these. Does that mean we are going to compose the Router with a SecurityBackend that would look like:

```
class SecurityBackend(object):
    def has_permission(self, name, obj, user):
        ....

    def get_queryset(self, user):
       ....
```

**Comment by jpic** [comment]
Or even, should we add a permission check method on model instance + a queryset security filter on the model manager and then reuse that. This would allow users to plug in their back end there while supporting easy default configuration ?

```
class SongManager(models.Manager):
    def get_queryset_for_user(self, user):
        ...

class Song(models.Model):
    objects = SongManager()

    def has_permission(self, codename, user):
         ....
