### ISSUE TITLE
Friendly override from external project

### ISSUE THREAD

**Issue by jpic** [yourlabs/crudlfap#48]
Project betagouv/mrs includes crudlfap but overrides the entry point, instead of [crudlfap/index.js](https://github.com/yourlabs/crudlfap/blob/master/js/index.js), it has its own [crudlfap.js](https://github.com/betagouv/mrs/blob/master/src/mrs/static/js/crudlfap.js).

The only reason for this, is the set of [StimulusJS added by betagouv/mrs](https://github.com/betagouv/mrs/tree/master/src/mrs/static/js/controllers). Their crudlfap.js entrypoint [ensures both crudlfap's and mrs projects controllers are loaded together](https://github.com/betagouv/mrs/blob/master/src/mrs/static/js/crudlfap.js#L35-L39). As you can see, there is a lot of duplicate code, for example, the IE fix has to move from mrs to crudlfap (issue #46).

To close this issue, crudlfap must expose a nice way for the other project to initiate the scripts and add its controller directory. For development, you might need to run the other project, in which case you will probably like the help of Rajesh.

Level: hard+

**Comment by jpic** [comment]
Hello @rajeshcis and @cis-navjot-g , have you started to work on this or can I reassign ? thanks

**Comment by rajeshcis** [comment]
@cis-navjot-g  was busy in IE browser test  issues and also he is on leave, so From Monday we will work on this

**Comment by jpic** [comment]
KK HaiChen it's all yours ;)

**Comment by jpic** [comment]
That's been fixed for a while in production ;)
