### ISSUE TITLE
Stablilize browser tests

### ISSUE THREAD

**Issue by jpic** [yourlabs/crudlfap#66]
I'm experiencing some random failures, on the test of the view title **after** login. It happens randomly, I think it's because of a race condition caused by the test moving forward to title test before the browser has time to finish loading the next page after submiting the login form.

To close this issue:

- drop the pause statement: https://github.com/yourlabs/crudlfap/blob/master/nightwatch/tests/test.ts#L44
- instead, use waitForElementVisible and wait for an element of the next page, before testing the title.

![2018-04-24-202206_711x363_scrot](https://user-images.githubusercontent.com/94636/39206369-82ca3e68-47fd-11e8-9a62-07aaa06ed0ee.png)
![2018-04-24-202131_511x360_scrot](https://user-images.githubusercontent.com/94636/39206370-82f0eb58-47fd-11e8-828b-217ec5a2b302.png)

**Comment by cis-navjot-g** [comment]
Done :)
