### ISSUE TITLE
Incorrect ordering of views and url matching

### ISSUE THREAD

**Issue by melvyn-sopacua** [yourlabs/crudlfap#8]
The default ordering matches DetailView before CreateView, because `/create/` matches `(?P<pk>[\w\d_-]+)/$`.
What's more disturbing is that after changing the order ListView matches before create:

```python
>>> from postfix.urls import urlpatterns
>>> urlpatterns
[<URLPattern 'create/$' [name='alias_create']>, <URLPattern '$' [name='alias_list']>, <URLPattern '(?P<pk>[\w\d_-]+)/delete/$' [name='alias_delete']>, <URLPattern '(?P<pk>[\w\d_-]+)/update/$' [name='alias_update']>, <URLPattern '(?P<pk>[\w\d_-]+)/$' [name='alias_detail']>]
```
If I switch order to put ListView first, then CreateView is not matched. The only explanation I have for it, is that there's a greedy match on slashes somewhere that is cut off before other matches are done. So `/postfix/create/` matches '$' because `/postfix/create/` is cut off instead of just `/postfix/`.

Reverse does the right thing:
```python
>>> reverse('alias_create')
'/postfix/create/'
>>> reverse('alias_list')
'/postfix/'
```

**Comment by jpic** [comment]
Yeah I remember this issue, it's really important to get the right order ([example](https://github.com/yourlabs/crudlfap/blob/master/src/crudlfap/apps.py#L23))

I really wonder if the $ works, because crudlfap [does generate urls with it](https://github.com/yourlabs/crudlfap/blob/master/src/crudlfap/test_routers.py).

However, we could probably fix that transparently in Router.urlpatterns(), and even raise an Exception when we detect an incompatibility ?

**Comment by jpic** [comment]
This should be fixed b977a8bf279102b80bb52cf549c7b90d8b0c5098

I think this was introduced by 1d47aab2ae99f61df03a46e7155388acbe444127, but would have been visible when using a slug too.

Thanks <3 <3 <3

**Comment by jpic** [comment]
But then, we should better not have a user with username 'create', not sure what's the best thing to do here, perhaps have `/model/create/new` ?

**Comment by melvyn-sopacua** [comment]
I did wonder why model name is stripped. Typically, you want one router per app, that handles multiple models. Or you want an AppRouter and a ModelRouter so you can declare as:
```python
     AppRouter(
         ModelRouter(Artist, generic.RoutableViews, **kwargs),
         ....
    ).urlpatterns()
```

I also think I know what the problem is. The patterns should all be anchored at the start. So the pattern for list should be `^$`, not `$`. The latter will always match, cause you're matching "if the string has an end".

**Comment by jpic** [comment]
Well, we could do an AppRouter, but yourapp.urls.urlpatterns is the app router, built with multiple model router. You can do urlpatterns = ArtistRouter.urlpatterns() + SongRouter.urlpatterns(). We could add an extra class, but what for ?

What model name is stripped and how ?

Might be a start anchor problem indeed !

**Comment by melvyn-sopacua** [comment]
https://github.com/yourlabs/crudlfap/blob/master/src/crudlfap/views/routable.py#L155

**Comment by jpic** [comment]
What view slug is not correctly autogenerated ?

Did you try overriding it ?

**Comment by jpic** [comment]
i'm making doc for you right now, got another issue to open btw !

**Comment by melvyn-sopacua** [comment]
Any.

Given: `url(r'^postfix/', include('postfix.urls'))` for a Router with model 'Alias', urlpatterns become:

* `/postfix/` => List
* `/postfix/create/` => Create
* etc..

No mention of 'Alias' in the url. Url names are correct.

**Comment by jpic** [comment]
oh, you want `/postfix/alias/`, `/postfix/alias/create/` and so on ? 

Did you try something like Router(url_prefix='alias') ?

**Comment by jpic** [comment]
I just had the same problem it turned out you were right and i have no idea why that was somehow working for me :dancer:

**Comment by jpic** [comment]
There is some rewriting to make in the url system, based on research from yourlabs/django-xcbv

For now, just have the create view before the detail view and it should work.

Please reopen if necessary.
